# ============== UITVIC Dataset Configuration ===================
# Enhanced configuration for UITVIC dataset training
# Compatible with both local development and Kaggle environments

# Data paths - will be automatically adjusted for environment
root: "dataset/uitvic_dataset"

# Training data
train_image_dir: "dataset/uitvic_dataset/coco_uitvic_train/coco_uitvic_train"
train_ann: "dataset/uitvic_dataset/uitvic_captions_train2017.json"

# Validation data (using test split for validation)
valid_image_dir: "dataset/uitvic_dataset/coco_uitvic_test/coco_uitvic_test"
valid_ann: "dataset/uitvic_dataset/uitvic_captions_test2017.json"

# Test data
test_image_dir: "dataset/uitvic_dataset/coco_uitvic_test/coco_uitvic_test"
test_ann: "dataset/uitvic_dataset/uitvic_captions_test2017.json"

# ============== Model Configuration ===================
# Pretrained model path - will be adjusted for environment
pretrained: 'weights/model_base_capfilt_large.pth'

# Vision Transformer settings
vit: 'base'  # 'base' or 'large'
vit_grad_ckpt: False
vit_ckpt_layer: 0

# ============== Training Configuration ===================
# Batch size - adjust based on GPU memory (REDUCED for RTX 3050 4GB)
batch_size: 2  # Reduced for 4GB GPU, will be auto-adjusted if needed

# Learning rate settings
init_lr: 1e-5
min_lr: 1e-7
weight_decay: 0.05

# Training epochs
max_epoch: 1  # Increased for better training

# Image processing
image_size: 384  # Fixed from incorrect value of 3

# ============== Generation Configuration ===================
# Caption generation settings
max_length: 35
min_length: 5
num_beams: 3

# Vietnamese prompt for UITVIC dataset
prompt: 'mot buc anh ve '

# ============== Advanced Settings ===================
# For debugging and monitoring
save_frequency: 1  # Save model every N epochs
eval_frequency: 1  # Evaluate every N epochs
log_frequency: 10  # Log every N batches

# Data loading
num_workers: 4  # Will be adjusted for stability if needed
pin_memory: True

# Mixed precision training (if supported)
use_amp: False

# Gradient clipping
max_grad_norm: 1.0

# Early stopping
patience: 3  # Stop if no improvement for N epochs
min_delta: 0.001  # Minimum improvement threshold