# ============== UITVIC Kaggle Configuration ===================
# Ultra-safe configuration specifically for Kaggle environment
# Designed to avoid tensor size mismatch and memory issues

# Data paths - will be automatically adjusted for Kaggle
root: "dataset/uitvic_dataset"

# Training data
train_image_dir: "dataset/uitvic_dataset/coco_uitvic_train/coco_uitvic_train"
train_ann: "dataset/uitvic_dataset/uitvic_captions_train2017.json"

# Validation data (using test split for validation)
valid_image_dir: "dataset/uitvic_dataset/coco_uitvic_test/coco_uitvic_test"
valid_ann: "dataset/uitvic_dataset/uitvic_captions_test2017.json"

# Test data
test_image_dir: "dataset/uitvic_dataset/coco_uitvic_test/coco_uitvic_test"
test_ann: "dataset/uitvic_dataset/uitvic_captions_test2017.json"

# ============== Model Configuration ===================
# Pretrained model path - will be adjusted for Kaggle
pretrained: 'weights/model_base_capfilt_large.pth'

# Vision Transformer settings
vit: 'base'  # 'base' or 'large'
vit_grad_ckpt: False
vit_ckpt_layer: 0

# ============== Training Configuration ===================
# Batch size - ULTRA CONSERVATIVE for Kaggle
batch_size: 1  # Single image per batch for Kaggle stability

# Learning rate settings
init_lr: 5e-6  # Lower learning rate for stability
min_lr: 1e-8
weight_decay: 0.02

# Training epochs
max_epoch: 1  # Single epoch for Kaggle testing

# Image processing - REDUCED for stability
image_size: 224  # Smaller image size for Kaggle

# ============== Generation Configuration ===================
# Caption generation settings - ULTRA SAFE
max_length: 15  # Much shorter for stability
min_length: 3
num_beams: 1    # NO beam search for Kaggle

# Vietnamese prompt for UITVIC dataset
prompt: 'mot buc anh ve '

# ============== Kaggle-Specific Settings ===================
# Ultra-conservative settings for Kaggle environment

# Data loading - minimal workers
num_workers: 0  # No multiprocessing for Kaggle
pin_memory: False  # Disable for stability

# Mixed precision training
use_amp: False  # Disable AMP

# Gradient settings
max_grad_norm: 0.5  # Lower gradient clipping

# Evaluation settings
eval_frequency: 1
save_frequency: 1
log_frequency: 5

# Early stopping
patience: 1
min_delta: 0.01

# Memory optimization
gradient_checkpointing: False
empty_cache_frequency: 10  # Clear cache every N batches